---
ecosConfig: 
    ip: 10.10.10.249
    tcpPort: 15471
    timeout: 1000
    protocol: DCC
    address: 189
rPiConfig:
    ip: 10.10.10.247
    tcpPort: 9999
    timeout: 1000
    serverPort: 9998
...