---
ecosConfig: 
    ip: 192.168.13.21
    tcpPort: 15471
    timeout: 1000
    protocol: DCC
    address: 196
    waitTillShutdown: 20
rPiConfig:
    ip: 192.168.13.22
    tcpPort: 9999
    timeout: 1000
    serverPort: 9998
vncConfig:
    path: C:\Program Files\TightVNC\
    viewerResolution:
        #width: 1920
        #height: 1080
        width: 1280
        height: 1024
    serverResolution:
        width: 1920
        height: 1080
        #width: 2560
        #height: 1413
    initTop: 0
    initLeft: 0
    stepSize: 50
...