---
ecosConfig: 
    ip: 10.10.10.249
    tcpPort: 15471
    timeout: 1000
    protocol: DCC
    address: 189
    waitTillShutdown: 20
rPiConfig:
    ip: 10.10.10.247
    tcpPort: 9999
    timeout: 1000
    serverPort: 9998
vncConfig:
    path: C:\Program Files\TightVNC\
    viewerResolution:
        #width: 1920
        #height: 1080
        width: 800
        height: 600
    serverResolution:
        #width: 2100
        #height: 1200
        width: 1920
        height: 1200
    initTop: 0
    initLeft: 0
    stepSize: 50
...